openshift:

  credentials:
    admin:
      username: "{{ CLUSTER_USERNAME }}"
      # Should be 14+ chars, upper and lower, with special characters
      password: "{{ CLUSTER_PASSWORD }}"
    users:
      - username: "admin"
        password: "{{ CLUSTER_PASSWORD }}"
        group: "cluster-admin"
      - username: "viewer"
        password: "{{ CLUSTER_PASSWORD }}"
        group: "cluster-admin"

  clusters:

    - name: local-machine
      type: local # local, hcp, rosa, aro
      domain: local-machine.domain.io
      create: false
      validate_certs: false
      workshop:
        chart:
          enabled: true
          name: rhoai-devex
          version: 0.2.3
          repo: https://poc-examples.github.io/workshops
      gitops:
        enabled: true
        channel: gitops-1.14
        namespace: openshift-gitops
      secrets:
        vault:
          enabled: true
        namespace: secrets-manager
        # Optional: This section optional creates additional user defined secrets.
        # The Secrets are placed in the set secrets.namespace and are accessible with the k8s clustersecretstore.
        pushSecrets: []
