openshift:

  aws:
    type: rosa
    # Name can only be 13 chars Max
    cluster_name: rosa-rhoai-5
    version: 4.16.18
    region: us-east-2
    workers: 7

  admin:
    credentials:
      username: "{{ CLUSTER_USERNAME }}"
      # Should be 14+ chars, upper and lower, with special characters
      password: "{{ CLUSTER_PASSWORD }}"

  # https://console.redhat.com/openshift/token/show
  offline_token: "{{ ROSA_TOKEN }}"

config:

  validate_certs: false

  gitops:
    enabled: true
    channel: gitops-1.14
    namespace: openshift-gitops

  workshop:
    chart:
      enabled: true
      name: rhoai-devex
      version: 0.2.1
      repo: https://poc-examples.github.io/workshops

  secrets:
    vault:
      enabled: true
    namespace: secrets-manager

    # Optional: This section optional creates additional user defined secrets.
    # The Secrets are placed in the set secrets.namespace and are accessible with the k8s clustersecretstore.
    pushSecrets: []
